import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)

RELAIS_UP_GPIO = 20
RELAIS_DOWN_GPIO = 21

GPIO.setup(RELAIS_UP_GPIO, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(RELAIS_DOWN_GPIO, GPIO.OUT, initial=GPIO.LOW)

GPIO.output(RELAIS_UP_GPIO, GPIO.HIGH)
GPIO.output(RELAIS_UP_GPIO, GPIO.LOW)

GPIO.cleanup()
